### ISSUE TITLE
Undefined reference to crc32 error when compiling

### ISSUE THREAD

**Issue by Quasimondo** [rogersce/cnpy#13]
When trying to compile a program that uses the cnpy::npz_save method I got an "undefined reference to `crc32'" error, which I did not get when using the cnpy::npy_save method.

I could resolve this by adding -lz to the g++ compilation line, so it looks like this:
g++ test.cpp -L/usr/local/lib -lcnpy -lz -o test

Just wanted to add this here in case other run into the same issue.

**Comment by han-qiu** [comment]
@Quasimondo  Thank you! Solved my problem.

**Comment by rogersce** [comment]
Thank you for pointing this out. I've updated the README to reflect this.

**Comment by immaraj** [comment]
Thanks, this helped me.

**Comment by kumar-saurabh2** [comment]
> When trying to compile a program that uses the cnpy::npz_save method I got an "undefined reference to `crc32'" error, which I did not get when using the cnpy::npy_save method.
> 
> I could resolve this by adding -lz to the g++ compilation line, so it looks like this:
> g++ test.cpp -L/usr/local/lib -lcnpy -lz -o test
> 
> Just wanted to add this here in case other run into the same issue.


Thank you so much! I also faced similar issue of `crc32' and it was fixed by adding -lz

**Comment by bored17** [comment]
i love you
