### ISSUE TITLE
cnpy::npy_save segfaults when numpy arrays are too large

### ISSUE THREAD

**Issue by abeconnelly** [rogersce/cnpy#17]
If the numpy arrays exceed the limits of `int`, saving into a numpy array doesn't work properly.

The following small code causes a segfault on my system:

```
#include "cnpy.h"
#include <cstdlib>

int main()
{
    size_t sz, idx;
    int *large_data;
    unsigned int shape[2];

    shape[0]=300;
    shape[1]=20000000;

    sz = (size_t)shape[0];
    sz *= (size_t)shape[1];

    large_data = (int *)malloc(sizeof(int)*sz);
    for (idx=0; idx<sz; idx++) {
      large_data[idx] = 0;
    }

    cnpy::npy_save("large-data.npy", large_data, shape, 2, "w");

    free(large_data);
}
```

To compile in the `cnpy` directory (after `cmake`, `make`, etc.):

```
 g++ -o write-large-file write-large-file.cpp -lcnpy -L. -I.
```

Looking at `npy_save` lines [109-110](https://github.com/rogersce/cnpy/blob/013d31d2e26143584c8aea4a2e986d603c723dea/cnpy.h#L109-L110) look to be the culprit as the `int` datatype for `nels` is overflowing when a `size_t` datatype would be more appropriate.

Though I haven't tested, it looks like PR 9 ["Various fixes and modernizations"](https://github.com/rogersce/cnpy/pull/9) would fix this issue.

**Comment by rogersce** [comment]
I just merged PR9 into master. It looks like it will fix your problem, please let me know if it doesn't and I'll take another look.
