### ISSUE TITLE
building fails after commit 6fafb0aa71cc2f66025325d5340bb25707264331

### ISSUE THREAD

**Issue by fgfuchs** [rogersce/cnpy#19]
zip.h: No such file or directory

**Comment by rogersce** [comment]
Libzip is now being used to read .npz files. Can you try installing it and then see if building works?

**Comment by davidHysom** [comment]
We have the same problem (Lawrence Livermore National Lab). It doesn't seem practical to install libzip, since we aren't admins on our various super computing platforms.

**Comment by fgfuchs** [comment]
I works, if I install libzip.
Maybe this could be made an optional dependency?

**Comment by rogersce** [comment]
Understood, I'll see what I can do tonight, either make it an optional dep or use zlib instead

**Comment by fgfuchs** [comment]
Thank you @rogersce for resolving this so quickly!
