### ISSUE TITLE
zlib not found if installed in a non-standard location

### ISSUE THREAD

**Issue by benjaminjeliot** [rogersce/cnpy#21]
I ran into an issue building when zlib was not installed in the default system location.

This could be fixed by using find_package to discover the zlib include and library paths, and allowing an alternative ZLIB_ROOT to be supplied at build time.

**Comment by benjaminjeliot** [comment]
I have created a pull request with the suggested fix #22

**Comment by chraibi** [comment]
Please accept this PR.

**Comment by rogersce** [comment]
I just merged it. thank you!
