### ISSUE TITLE
Error while loading saved .npy in python.

### ISSUE THREAD

**Issue by asafben** [rogersce/cnpy#23]
Hi,
Iv'e tried saving the following data type:
std::vector<std::vector<float> > data;

as follows:
cnpy::npy_save(path, &data[0], {nz_, ny_, nx_}, "w");
(the outer vector is of size: nx_ * ny_ * nz_)

and while trying in python:
d = np.load('path/grid.npy')

i'm getting the following error:
Traceback (most recent call last):
  File ".../lib/python3.5/site-packages/numpy/lib/format.py", line 510, in _read_array_header
    dtype = numpy.dtype(d['descr'])
TypeError: data type "<?24" not understood

How (or should) I consider the size of the inner vector?
Should I load the .npy differently in Python?

Thank you for your help.

**Comment by chraibi** [comment]
Please post a complete working example.

**Comment by rogersce** [comment]
Trying to directly load and save vectors of vectors isn't going to work -- the data isn't laid out contiguously in memory. 

Please take a look at issue #20 for loading 2D data from file, into a vector of vectors.

To save a vector of vectors, you first need to copy it to a contiguous block of memory, e.g.

```c++
//data is a std::vector<std::vector<double>>. Each sub-vector should have the same size.
size_t N = data.size();
size_t M = data[0].size();

std::vector<double> raw(N*M);

for(int row = 0;row < N; row++) {
   for(int col = 0;col < M; col++) {
      raw[row*M+col] = data[row][col];
   }
}

cnpy::npy_save("arr1.npy",&raw[0],{N,M},"w");
```

**Comment by asafben** [comment]
Excellent! It was very helpful, thank you.
