### ISSUE TITLE
Replace abort() with error codes or exceptions

### ISSUE THREAD

**Issue by justanotheruser** [rogersce/cnpy#26]
Program using cnumpy aborts at first sight of non-standard situation. It would be easier to use in something more complex than laboratory exercises if we replace abort() with exceptions or error codes. I can do it and create pull request, but I wanted to know, which way would be preferable?  I no one answers, I'll send exception version in a few days.

**Comment by rogersce** [comment]
Thanks for pointing this out. I replaced the 3 abort commands with exceptions, so going to close this issue.
