### ISSUE TITLE
Undefined references

### ISSUE THREAD

**Issue by shivaang12** [rogersce/cnpy#36]
When I load .npy file I get this..

![00001](https://user-images.githubusercontent.com/9318164/42232881-dc7cde56-7ebd-11e8-99ef-f3d552d80c96.png)

**Comment by rogersce** [comment]
Did you enable zlib during installation? In cmakelists.txt there should be an option for it

**Comment by rogersce** [comment]
Ah I didn't notice you were using a static lib. When you compile whatever your program is, try adding -lz to link to zlib

**Comment by shivaang12** [comment]
Ahh.. It worked. Thank you!
