### ISSUE TITLE
cnpy::npz_load segfaults when loading large numpy array

### ISSUE THREAD

**Issue by avitalsh** [rogersce/cnpy#37]
Hi,

I'm trying to load an npz file that has 4 numpy arrays with the following number of elements:
arr1: 125, arr2: 6250, arr3: 245000, arr4: 1000.

when trying to read the data stored in arr3 I get a segfault:

`    cnpy::NpyArray arr3 = cnpy::npz_load(npz_path, "arr3");
    
    double* loaded_data = arr3.data<double>();
    
    vector<double> vec;
    
    for(int i = 0; i < arr3.num_vals; i++){
        vec.push_back(loaded_data[i]);
    }`
Thanks

**Comment by LeilyR** [comment]
@avitalsh  I ran to the same issue for big matrices, I wonder if you found a solution for that. Thanks!

**Comment by avitalsh** [comment]
@LeilyR yes, it was due to type conversion. Take a look at this issue - https://github.com/rogersce/cnpy/issues/24
This solved my problem.

**Comment by LeilyR** [comment]
thanks a million!
