### ISSUE TITLE
Centos 7.4

### ISSUE THREAD

**Issue by tonyreina** [rogersce/cnpy#47]
> undefined reference to `cnpy::npz_load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'

I'm taking a project that compiles and runs on Ubuntu 16.04 to CentOS 7.4.  For some reason, CentOS is not detecting the `cnpy` library.  I've done the make/make install on the device and copied the libcnpy.a/.so everywhere I can think.

Anyone have an idea of why it is still having trouble finding the library?

Thanks

**Comment by TynanK** [comment]
Hi Tony,

I'm having the same issue, and it's kind of driving me up the wall. Did you ever figure it out?

Best regards,
Tynan

EDIT: The issue seems to have been either an outdated or mismatched GNU compiler. GNU 7.2.0 was installed on the system, but cmake was using GNU 4.8.5

**Comment by Zening-Li** [comment]
hello, Tynan,
I also meet the same problem. Did you ever figure it out?

**Comment by TynanK** [comment]
Hello Zening-Li,

Yes, I did figure out what the problem was, at least on my machine. I was
unintentionally running cmake with an outdated GNU compiler. Once I
directed it to the updated version, everything worked properly. Hopefully
that’s all you need to do too!

Best regards,
Tynan
