### ISSUE TITLE
usage at the platform of windows

### ISSUE THREAD

**Issue by mwsunshine** [rogersce/cnpy#60]
hi，

Thank you for your great work! I notice your guideline for installation is for linux. Is it possible to use this lib on windows?

best wishes,

Matthew

**Comment by sutongkui** [comment]
I just copied the .h and .cpp to my project(in a visual studio project), and met the compile error, 

`1>cnpy.obj : error LNK2019: unresolved external symbol inflate referenced in function "struct cnpy::NpyArray __cdecl load_the_npz_array(struct _iobuf *,unsigned int,unsigned int)" (?load_the_npz_array@@YA?AUNpyArray@cnpy@@PEAU_iobuf@@II@Z)  

1>cnpy.obj : error LNK2019: unresolved external symbol inflateEnd referenced in function "struct cnpy::NpyArray __cdecl load_the_npz_array(struct _iobuf *,unsigned int,unsigned int)" (?load_the_npz_array@@YA?AUNpyArray@cnpy@@PEAU_iobuf@@II@Z)  

1>cnpy.obj : error LNK2019: unresolved external symbol inflateInit2_ referenced in function "struct cnpy::NpyArray __cdecl load_the_npz_array(struct _iobuf *,unsigned int,unsigned int)" (?load_the_npz_array@@YA?AUNpyArray@cnpy@@PEAU_iobuf@@II@Z)`

**Comment by Lala5th** [comment]
Looks like you are missing Zlib, though I am not 100% sure.
To the initial question: I think if you can use cmake on windows you can still use the install directions(mostly) and you can link the libraries, but I had no experience with cmake on windows so I am unsure

**Comment by sutongkui** [comment]
you are right, i installed zlib and it works well.
