### ISSUE TITLE
Incorrect results when loading a float32 array

### ISSUE THREAD

**Issue by netw0rkf10w** [rogersce/cnpy#62]
Hello,

I would like to report a potential bug in the software: when loading a `float32` numpy array, it gives incorrect values. I spent a while on this bug before realizing that converting the numpy array to `float64` before saving makes it work.

Best regards.

**Comment by netw0rkf10w** [comment]
Sorry, this was because I loaded it as `double`. I changed to `float` and it works.

**Comment by Joevaen** [comment]
> Sorry, this was because I loaded it as `double`. I changed to `float` and it works.

Hi, could you please tell me how to check data of the array loaded via the type `cnpy::NpyArray`?

**Comment by netw0rkf10w** [comment]
@Joevaen I just followed [this example](https://github.com/rogersce/cnpy/blob/master/example1.cpp), which is quite straightforward.
