### ISSUE TITLE
row-major or col-major?

### ISSUE THREAD

**Issue by poor1017** [rogersce/cnpy#64]
Hi @rogersce 

    Thank you for your work.

    I am working on reading data from .npy.

`cnpy::NpyArray mat = cnpy::npy_load(file);`
`int row = mat.shape[0];`
`int col = mat.shape[1];`
`float* data = mat.data<float>();`

    For some npy files, I should read in col-major to get correct form;
`for (int r = 0; r < row; ++r) {for (int c = 0; c < col; ++c) {egn(r, c) = data[offset]; ++offset;}}`

    And for the other npy files, I should read in row-major to get correct form;

`for (int c = 0; c < col; ++c) {for (int r = 0; r < row; ++r) {egn(r, c) = data[offset]; ++offset;}}`

    I do not know when row-major and when col-major.

**Comment by RunOrVeith** [comment]
For anyone else stumbling across this:
Numpy stores data in row-major by default, but Eigen in column-major.

So in order to load the data correctly, you have to do the following

```C++
    cnpy::npz_t loadedNpz = cnpy::npz_load(file.string());
    cnpy::NpyArray npPositions = loadedNpz["positions"];

    // YOU HAVE TO BE CAREFUL, NUMPY STORES DATA IN ROW-MAJOR, BUT EIGEN in COLUMN-MAJOR BY DEFAULT
    float *positionsArray = npPositions.data<float>();
    Eigen::MatrixX3f positions;
    positions = Eigen::Map<Eigen::Matrix<float, Eigen::Dynamic, 3, Eigen::RowMajor>>(positionsArray, npPositions.shape[0], npPositions.shape[1]);
```

If you load something that is square (e.g. a 4x4 matrix), it will appear to be transposed if you don't specify the `Eigen::RowMajor` flag. If you load something non-square (e.g 100x3), it will be completely different to the original data order if you don't specify the flag.

**Comment by firdota** [comment]
if the var "fortran_order" in struct NpyArray is TRUE, then col-oder; else row-oder

**Comment by poor1017** [comment]
Thank you two.

**Comment by csyhping** [comment]
> For anyone else stumbling across this: Numpy stores data in row-major by default, but Eigen in column-major.
> 
> So in order to load the data correctly, you have to do the following
> 
> ```c++
>     cnpy::npz_t loadedNpz = cnpy::npz_load(file.string());
>     cnpy::NpyArray npPositions = loadedNpz["positions"];
> 
>     // YOU HAVE TO BE CAREFUL, NUMPY STORES DATA IN ROW-MAJOR, BUT EIGEN in COLUMN-MAJOR BY DEFAULT
>     float *positionsArray = npPositions.data<float>();
>     Eigen::MatrixX3f positions;
>     positions = Eigen::Map<Eigen::Matrix<float, Eigen::Dynamic, 3, Eigen::RowMajor>>(positionsArray, npPositions.shape[0], npPositions.shape[1]);
> ```
> 
> If you load something that is square (e.g. a 4x4 matrix), it will appear to be transposed if you don't specify the `Eigen::RowMajor` flag. If you load something non-square (e.g 100x3), it will be completely different to the original data order if you don't specify the flag.

hi @RunOrVeith , i tried with both Eigne::RowMajor and Eigen::ColMajor, the results are same. I need to call .transpose() to get the same data as numpy. Could you help with this? Thanks.
