### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by sb-git-cloud** [rogersce/cnpy#70]
Hi I am trying to install CNPY by following the instructions, but always get the following error after "make":

[ 20%] Linking CXX shared library libcnpy.dylib
Undefined symbols for architecture x86_64:
  "_inflate", referenced from:
      load_the_npz_array(__sFILE*, unsigned int, unsigned int) in cnpy.cpp.o
  "_inflateEnd", referenced from:
      load_the_npz_array(__sFILE*, unsigned int, unsigned int) in cnpy.cpp.o
  "_inflateInit2_", referenced from:
      load_the_npz_array(__sFILE*, unsigned int, unsigned int) in cnpy.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libcnpy.dylib] Error 1
make[1]: *** [CMakeFiles/cnpy.dir/all] Error 2
make: *** [all] Error 2

I am not experienced and thought that it might have something to do with Zlib which I installed via homebrew, but it didn't solve the issue. I am using Mac OS 10.15.6. Does anyone have a hint for the installation? I would highly appreciate any help. Thanks so much.

**Comment by symisc** [comment]
You must link it with the **zlib library**.

**Comment by sb-git-cloud** [comment]
Thanks! It was an error caused by adding cnpy as a shared instead of static library
